#!/usr/bin/env python3
from pathlib import Path
import sys

root = Path(sys.argv[1] if len(sys.argv) > 1 else "kernel")
boardids = root / "include/hsad/config_boardids.h"
total = root / "drivers/huawei/hsad/config_total_product.c"
k3oem = root / "drivers/huawei/hsad/auto-generate/hw_k3oem_configs.c"

for p in (boardids, total):
    if not p.exists():
        raise SystemExit(f"missing required source: {p}")

# Restore the generic Huawei K3 OEM profile used by boardid 0.
k3oem.parent.mkdir(parents=True, exist_ok=True)
if not k3oem.exists():
    k3oem.write_text(r'''/*The file is auto generated by tools, don't modify it manully.*/
#include <hsad/configdata.h>
config_pair  hw_k3oem_configs [] = {
    {"arch/arch_type", (unsigned int)1, E_CONFIG_DATA_TYPE_INT },
    {"audio/audience", (const unsigned int)(unsigned int*)"ES305", E_CONFIG_DATA_TYPE_STRING },
    {"audio/digital_mic", (unsigned int)0, E_CONFIG_DATA_TYPE_INT },
    {"audio/dual_mic", (unsigned int)1, E_CONFIG_DATA_TYPE_INT },
    {"audio/hs_keys", (unsigned int)1, E_CONFIG_DATA_TYPE_INT },
    {"audio/hs_pa", (const unsigned int)(unsigned int*)"NONE", E_CONFIG_DATA_TYPE_STRING },
    {"audio/hsd_invert", (unsigned int)1, E_CONFIG_DATA_TYPE_INT },
    {"audio/ril_type", (const unsigned int)(unsigned int*)"NONE", E_CONFIG_DATA_TYPE_STRING },
    {"audio/spk_pa", (const unsigned int)(unsigned int*)"NONE", E_CONFIG_DATA_TYPE_STRING },
    {"audio/spk_route", (const unsigned int)(unsigned int*)"SPK", E_CONFIG_DATA_TYPE_STRING },
    {"battery/battery_type", (unsigned int)0, E_CONFIG_DATA_TYPE_INT },
    {"board/board_type", (unsigned int)0, E_CONFIG_DATA_TYPE_INT },
    {"camera/camera_timing_type", (unsigned int)1, E_CONFIG_DATA_TYPE_INT },
    {"camera/faceIgnoreCount", (unsigned int)9, E_CONFIG_DATA_TYPE_INT },
    {"camera/primary_sensor", (unsigned int)90, E_CONFIG_DATA_TYPE_INT },
    {"camera/secondary_sensor", (unsigned int)270, E_CONFIG_DATA_TYPE_INT },
    {"iomux/iomux_type", (unsigned int)0, E_CONFIG_DATA_TYPE_INT },
    {"keypad/keypad_type", (unsigned int)0, E_CONFIG_DATA_TYPE_INT },
    {"lcd/lcd_type", (unsigned int)0, E_CONFIG_DATA_TYPE_INT },
    {"product/name", (const unsigned int)(unsigned int*)"k3oem", E_CONFIG_DATA_TYPE_STRING },
    {"sensor/sensor_type", (unsigned int)0, E_CONFIG_DATA_TYPE_INT },
    {"touchscreen/touchscreen_type", (unsigned int)0, E_CONFIG_DATA_TYPE_INT },
    {"usbphy/usbphy_type", (unsigned int)0, E_CONFIG_DATA_TYPE_INT },
    {0, 0, 0}
 };
struct board_id_general_struct config_common_k3oem= {
    .name=COMMON_MODULE_NAME,
    .board_id=BOARD_ID_K3OEM,
    .data_array={.config_pair_ptr=hw_k3oem_configs},
    .list={NULL,NULL},
};
''')

s = boardids.read_text()
if "BOARD_ID_K3OEM" not in s:
    marker = "#endif"
    if marker not in s:
        raise SystemExit("config_boardids.h missing #endif")
    s = s.replace(marker, "#define BOARD_ID_K3OEM 0x00\n" + marker, 1)
    boardids.write_text(s)

s = total.read_text()
inc = '#include "auto-generate/hw_k3oem_configs.c"'
if inc not in s:
    anchor = '#include <hsad/config_boardids.h>'
    if anchor not in s:
        raise SystemExit("config_total_product.c include anchor missing")
    s = s.replace(anchor, anchor + "\n" + inc, 1)

entry = "    &config_common_k3oem,"
if entry not in s:
    anchor = "struct board_id_general_struct  *hw_ver_total_configs[] = \n{\n"
    if anchor not in s:
        anchor = "struct board_id_general_struct *hw_ver_total_configs[] =\n{\n"
    if anchor not in s:
        raise SystemExit("hw_ver_total_configs array anchor missing")
    s = s.replace(anchor, anchor + entry + "\n", 1)
total.write_text(s)

bs = boardids.read_text()
ts = total.read_text()
ks = k3oem.read_text()
assert "#define BOARD_ID_K3OEM 0x00" in bs
assert inc in ts
assert entry in ts
assert '.board_id=BOARD_ID_K3OEM' in ks
assert '"product/name"' in ks and '"k3oem"' in ks
assert '"iomux/iomux_type", (unsigned int)0' in ks

print("V408_K3OEM_PATCH=PASS")
print("BOARD_ID_K3OEM=0x00")
print("PROFILE=config_common_k3oem")
print("PRODUCT=k3oem")
print("IOMUX_TYPE=0")
print("PROFILE_SOURCE=OEM_K3V2_HSAD")
